import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const packageRoot = path.resolve(__dirname, '..')
const swiftResourcesRoot = path.resolve(packageRoot, '../clippy-swift/Sources/ClippySwift/Resources')
const assetsRoot = path.resolve(packageRoot, 'src/assets')
const generatedRoot = path.resolve(packageRoot, 'src/generated')
const generatedFile = path.resolve(generatedRoot, 'packs.ts')

const packs = [
  ['clippy', 'Clippy'],
  ['cat', 'Cat'],
  ['rocky', 'Rocky']
]

function toIdentifier(value) {
  const alphanumeric = value.replace(/[^A-Za-z0-9]+/g, ' ')
  const parts = alphanumeric
    .trim()
    .split(/\s+/)
    .filter(Boolean)

  if (parts.length === 0) {
    return 'animation'
  }

  const [first, ...rest] = parts
  let identifier = first.charAt(0).toLowerCase() + first.slice(1)
  identifier += rest
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  identifier = identifier.replace(/^[^A-Za-z_]+/, '')
  if (/^\d/.test(identifier)) {
    identifier = `n${identifier}`
  }
  return identifier || 'animation'
}

function buildAnimationConstant(constName, animationNames) {
  const used = new Map()
  const lines = [`export const ${constName} = {`]

  for (const animationName of animationNames) {
    const base = toIdentifier(animationName)
    const count = used.get(base) ?? 0
    used.set(base, count + 1)
    const identifier = count === 0 ? base : `${base}${count + 1}`
    lines.push(`  ${identifier}: ${JSON.stringify(animationName)},`)
  }

  lines.push('} as const')
  lines.push('')
  return lines.join('\n')
}

function buildAnimationMetadataConstant(constName, manifest) {
  const lines = [`export const ${constName} = {`]

  for (const animation of manifest.animations) {
    const animationFrames = manifest.frames.slice(
      animation.startFrame,
      animation.startFrame + animation.frameCount
    )
    const duration = animationFrames.reduce((total, frame) => total + frame.duration, 0)
    lines.push(`  ${JSON.stringify(animation.name)}: { duration: ${duration}, loops: ${animation.loops} },`)
  }

  lines.push('} as const')
  lines.push('')
  return lines.join('\n')
}

await mkdir(assetsRoot, { recursive: true })
await mkdir(generatedRoot, { recursive: true })

const generatedSections = [
  '// Generated by scripts/generate-assets.mjs.',
  "import type { CharacterName } from '../core/types'",
  ''
]

for (const [characterName, directoryName] of packs) {
  const swiftDirectory = path.join(swiftResourcesRoot, directoryName)
  const outputDirectory = path.join(assetsRoot, directoryName)
  const manifestSource = path.join(swiftDirectory, 'manifest.json')
  const atlasSource = path.join(swiftDirectory, 'atlas.png')
  const manifestDestination = path.join(outputDirectory, 'manifest.json')
  const atlasDestination = path.join(outputDirectory, 'atlas.png')

  await mkdir(outputDirectory, { recursive: true })
  await copyFile(manifestSource, manifestDestination)
  await copyFile(atlasSource, atlasDestination)

  const manifest = JSON.parse(await readFile(manifestSource, 'utf8'))
  const animationNames = manifest.animations.map((animation) => animation.name)
  const constantName = `${directoryName}Animation`
  const metadataName = `${directoryName}AnimationMetadata`
  const typeName = `${directoryName}AnimationName`

  generatedSections.push(buildAnimationConstant(constantName, animationNames))
  generatedSections.push(buildAnimationMetadataConstant(metadataName, manifest))
  generatedSections.push(`export type ${typeName} = (typeof ${constantName})[keyof typeof ${constantName}]`)
  generatedSections.push('')
}

generatedSections.push('export const builtInCharacterPacks = {')
for (const [characterName, directoryName] of packs) {
  const constantName = `${directoryName}Animation`
  const metadataName = `${directoryName}AnimationMetadata`
  generatedSections.push(`  ${characterName}: {`)
  generatedSections.push(`    character: ${JSON.stringify(characterName)} as CharacterName,`)
  generatedSections.push(`    displayName: ${JSON.stringify(directoryName)},`)
  generatedSections.push(`    atlasUrl: new URL('../assets/${directoryName}/atlas.png', import.meta.url).href,`)
  generatedSections.push(`    manifestUrl: new URL('../assets/${directoryName}/manifest.json', import.meta.url).href,`)
  generatedSections.push(`    animationNames: Object.values(${constantName}),`)
  generatedSections.push(`    animationMetadata: ${metadataName},`)
  generatedSections.push('  },')
}
generatedSections.push('} as const')
generatedSections.push('')
generatedSections.push('export type BuiltInCharacterPack = typeof builtInCharacterPacks[CharacterName]')
generatedSections.push('')

await writeFile(generatedFile, `${generatedSections.join('\n')}\n`)
